build(deps-dev): Bump lint-staged from 15.4.1 to 15.4.3 (#980)
Bumps [lint-staged](https://github.com/lint-staged/lint-staged) from 15.4.1 to 15.4.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/lint-staged/lint-staged/releases">lint-staged's releases</a>.</em></p>
<blockquote>
<h2>v15.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1512">#1512</a> <a href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a> Thanks <a href="https://github.com/tarik02"><code>@​tarik02</code></a>! - Adjust TypeScript types for the default export so that it can be used as a value without error TS2693.</li>
</ul>
<h2>v15.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1509">#1509</a> <a href="https://github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18"><code>8827ebf</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Change <em>lint-staged</em>'s dependencies to use <a href="https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004">caret (<code>^</code>) ranges</a> instead of <a href="https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1">tilde (<code>~</code>)</a>. This makes it easier for package managers to perform dependency management when minor-level updates are also permitted instead of just patch-level.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/lint-staged/lint-staged/blob/master/CHANGELOG.md">lint-staged's changelog</a>.</em></p>
<blockquote>
<h2>15.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1512">#1512</a> <a href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a> Thanks <a href="https://github.com/tarik02"><code>@​tarik02</code></a>! - Adjust TypeScript types for the default export so that it can be used as a value without error TS2693.</li>
</ul>
<h2>15.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1509">#1509</a> <a href="https://github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18"><code>8827ebf</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Change <em>lint-staged</em>'s dependencies to use <a href="https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004">caret (<code>^</code>) ranges</a> instead of <a href="https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1">tilde (<code>~</code>)</a>. This makes it easier for package managers to perform dependency management when minor-level updates are also permitted instead of just patch-level.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/lint-staged/lint-staged/commit/e53f950dd74255226f8ecdcfe0aa0a9ebd820277"><code>e53f950</code></a> chore(changeset): release</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/089da567b48af34a70a35552a1f27c4706bbd1b4"><code>089da56</code></a> test: fail Jest when coverage is under 100%</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/19aa461358ecf194fdd22366b3b94026656e033b"><code>19aa461</code></a> ci: remove code coverage action since it's not working in PRs from forks</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a> fix: update types.d.ts (<a href="https://redirect.github.com/lint-staged/lint-staged/issues/1512">#1512</a>)</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/aef9e5c83473505665f1d27c350cad1abc831a17"><code>aef9e5c</code></a> chore(changeset): release (<a href="https://redirect.github.com/lint-staged/lint-staged/issues/1510">#1510</a>)</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18"><code>8827ebf</code></a> build(dependencies): update dependencies and switch to caret ranges (<a href="https://redirect.github.com/lint-staged/lint-staged/issues/1509">#1509</a>)</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/7f69b3f5058d88050dbcef94218a15cc82e28600"><code>7f69b3f</code></a> docs: generalize description from 'linting' to 'tasks' (<a href="https://redirect.github.com/lint-staged/lint-staged/issues/1507">#1507</a>)</li>
<li>See full diff in <a href="https://github.com/lint-staged/lint-staged/compare/v15.4.1...v15.4.3">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=lint-staged&package-manager=npm_and_yarn&previous-version=15.4.1&new-version=15.4.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>